


class GremlinServerErrorStatusCodes:
    # move this to gremlin module
    ERROR_401 = "UNAUTHORIZED"
    ERROR_403 = "FORBIDDEN"
    ERROR_407 = "AUTHENTICATE"
    ERROR_497 = "REQUEST ERROR SERIALIZATION"
    ERROR_498 = "REQUEST ERROR MALFORMED REQUEST"
    ERROR_499 = "REQUEST ERROR INVALID REQUEST ARGUMENTS"
    ERROR_500 = "SERVER ERROR"
    ERROR_596 = "SERVER ERROR TEMPORARY"
    ERROR_597 = "SERVER ERROR EVALUATION"
    ERROR_598 = "SERVER ERROR TIMEOUT"
    ERROR_599 = "SERVER ERROR SERIALIZATION"
