import os

__VERSION__ = "0.0.4"


GREMLIN_SERVER_URL = os.environ.get("GREMLIN_SERVER_URL")
GREMLIN_SERVER_USERNAME = os.environ.get("GREMLIN_SERVER_USERNAME")
GREMLIN_SERVER_PASSWORD = os.environ.get("GREMLIN_SERVER_PASSWORD")
GREMLIN_TRAVERSAL_SOURCE = os.environ.get("GREMLIN_TRAVERSAL_SOURCE", "g")

DEBUG = os.environ.get("DEBUG", False)
SERVER_PORT = os.environ.get("SERVER_PORT", 8201)

DEFAULT_QUERY_TIMEOUT = 180
DEFAULT_QUERY_PAGINATION_SIZE = 20
