name: Docker Build Push

on:
  push:
    tags:
      - '*'

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    name: Publish docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: invanalabs/invana-engine
          tag_with_ref: true
          tags: latest
